// Generated by CoffeeScript 2.7.0
import {
  test,
  expect
} from '@playwright/test';

import {
  _electron as e
} from 'playwright';

test("it contains the word 'Electron'", async function() {
  var app, window;
  app = (await e.launch({
    executablePath: "./dist/civet2typescript-1.0.0.AppImage"
  }));
  window = (await app.firstWindow());
  return expect(window.getByText('Electron')).toBeVisible();
});
