// Generated by CoffeeScript 2.7.0
var app, input, output, window;

import {
  test,
  expect
} from '@playwright/test';

import {
  GetApp
} from './helpers';

app = window = input = output = null;

test.beforeAll(async function() {
  app = (await GetApp());
  window = (await app.firstWindow());
  input = (await window.locator('#input'));
  return output = (await window.locator('#output'));
});

test.afterAll(async function() {
  return (await app.close());
});

test("it contains the word 'Electron'", function() {
  return expect(window.getByText('Electron')).toBeVisible();
});

test('it produces the output', async function() {
  await input.pressSequentially("console.log 'a string'", {
    delay: 100
  });
  return expect(output).toContainText('console.log("a string");');
});
