// Generated by CoffeeScript 2.7.0
var GetApp, executablePath, version;

import fs from 'fs';

({version} = JSON.parse(fs.readFileSync('./package.json', 'utf8')));

executablePath = `./dist/civet2typescript-${version}.AppImage`;

import {
  _electron as e
} from 'playwright';

GetApp = function() {
  return e.launch({executablePath});
};

export {
  GetApp
};
